---
# list of roles to install via ansible-galaxy

collections:
  - name: community.kubernetes
    version: 1.2.0

  - name: community.general
    version: 1.2.0

  - name: community.aws
    version: 1.5.0

  - name: amazon.aws
    version: 1.5.0

  - name: community.crypto
    version: 1.8.0
